# .bashrc -*- shell-script -*-

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# Common variables
export LESS=eiM
export LESSCHARSET=utf-8
export PAGER='less -Rf'
export PRINTER=lp
export INPUTRC="~/.inputrc"
export HISTSIZE=9000
export HISTFILESIZE=9000

# Prompts
BLACK='\e[1;30m'
red='\e[0;31m'
RED='\e[1;31m'
green='\e[0;32m'
GREEN='\e[1;32m'
yellow='\e[0;33m'
YELLOW='\e[1;33m'
blue='\e[0;34m'
BLUE='\e[1;34m'
cyan='\e[0;36m'
CYAN='\e[1;36m'
NC='\e[0m'

PS1="\[${GREEN}\]\h:[\!] \W# \[${NC}\]"

# Aliases

alias   be='bundle exec'
alias   cl=clear
alias   h=history
alias   j=jobs
alias   ls='ls -F --color'
alias   l='ls -F'
alias   ll='ls -Fl'
alias   lh='ls -Flhs'
alias   lx='ls -FLl'
alias   la='ls -Fla'
alias   m='less'
alias   pu=pushd
alias   po=popd

alias   sc=systemctl
alias   jc=journalctl

complete -F _systemctl sc
complete -F _journalctl jc

# Use ssh by default with rsync
export RSYNC_RSH="ssh"

#
# Filename completions
#
shopt -s extglob
